web/router.ex
defmodule VolnaApi.Router do
  use VolnaApi.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :browser_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.EnsureAuthenticated, handler: VolnaApi.Token
    plug Guardian.Plug.LoadResource
  end

  scope "/", VolnaApi do
    pipe_through :browser # Use the default browser stack
    resources "/sessions", SessionController, only: [:create, :delete]
    get "/", LandingPageController, :index
    get "/privacy", LandingPageController, :privacy
    get "/privacy/eng", LandingPageController, :privacy_eng
    get "/login", SessionController, :new
    get "/logout", SessionController, :delete
    resources "/create", ProspectController, only: [:create]
  end

  scope "/", VolnaApi do
    pipe_through [:browser, :browser_auth]
    resources "/users", UserController, only: [:show, :index, :update, :new, :create]
    get "/radiostations", RadioStationController, :show
    get "/prospects", ProspectController, :index
    get "/devices", DeviceController, :index
    resources "/radiostations", RadioStationController, only: [:update, :create, :delete, :new, :edit]
    resources "/healthchecks", HealthCheckController, only: [:index, :show]
  end


  scope "/api", VolnaApi do
    pipe_through :api

    resources "/radiostations", RadioStationController, only: [:index]
  end
end

web/views/layout_view.ex
defmodule VolnaApi.LayoutView do
  use VolnaApi.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Русское радио приложение для айфона и айпад">
    <meta name="author" content="Radio Plus">
    <meta name="keywords" content="радио, айфон, russian radio">
    <meta name="google-site-verification" content="C4EKyd9iSujDBy3YQlRq5n3PIpcTyPAt5W_tmKz_EKc" />

    <%= render_existing(@view_module, "meta." <> @view_template, assigns) %>
    <title>Русское Радио - Русское радио в телефоне</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300" rel="stylesheet">
  </head>


  <body>
    <div class="container">
    <%# <header class="header"> %>
      <%# <nav role="navigation"> %>
        <%# <ul class="nav nav-pills pull-right"> %>
          <%# <% render "sign_in_sign_out.html", conn: @conn<br><br> %>
        <%# </ul> %>
      <%# </nav> %>
    <%# </header> %>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/layout/sign_in_sign_out.html.eex
<%= if logged_in?(@conn) do %>
  <%= link "Sign out", to: session_path(@conn, :delete, :access),
      method: :delete, class: "btn btn-danger" %><br>
  <%= current_user(@conn).email %>
<% end %>