web/router.ex
defmodule VolnaApi.Router do
  use VolnaApi.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :browser_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.EnsureAuthenticated, handler: VolnaApi.Token
    plug Guardian.Plug.LoadResource
  end

  scope "/", VolnaApi do
    pipe_through :browser # Use the default browser stack
    resources "/sessions", SessionController, only: [:create, :delete]
    get "/", LandingPageController, :index
    get "/privacy", LandingPageController, :privacy
    get "/privacy/eng", LandingPageController, :privacy_eng
    get "/login", SessionController, :new
    get "/logout", SessionController, :delete
    resources "/create", ProspectController, only: [:create]
  end

  scope "/", VolnaApi do
    pipe_through [:browser, :browser_auth]
    resources "/users", UserController, only: [:show, :index, :update, :new, :create]
    get "/radiostations", RadioStationController, :show
    get "/prospects", ProspectController, :index
    get "/devices", DeviceController, :index
    resources "/radiostations", RadioStationController, only: [:update, :create, :delete, :new, :edit]
    resources "/healthchecks", HealthCheckController, only: [:index, :show]
  end


  scope "/api", VolnaApi do
    pipe_through :api

    resources "/radiostations", RadioStationController, only: [:index]
  end
end

web/controllers/landing_page_controller.ex
defmodule VolnaApi.LandingPageController do
  use VolnaApi.Web, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end

  def privacy(conn, _params) do
    render(conn, "privacy.html")
  end

  def privacy_eng(conn, _params) do
    render(conn, "privacy_eng.html")
  end
end

web/views/landing_page_view.ex
defmodule VolnaApi.LandingPageView do
  use VolnaApi.Web, :view
end

web/templates/landing_page/index.html.eex
<div class="landing-page-container">
  <div class="welcome">

    <%# <h2 class="greeting-text"> Добро Пожаловать На Радио Плюс </h2> %>
  </div>

  <div class="landing">
    <div class="iphone-container">
      <div class="iphone-pic">
      </div>
    </div>
    <div class="description-container">
      <p class="welcome-text">Ваши любимые радиостанции у вас в кармане </p>
      <div class="description-text">
        <div class="logo"></div>
        <p class="greeting-text">Радиоскоп</p>
        <div class="subscribe-container">
          <a class ="soon" href="https://itunes.apple.com/us/app/%D1%80%D0%B0%D0%B4%D0%B8%D0%BE%D1%81%D0%BA%D0%BE%D0%BF/id1221693171?ls=1&mt=8"><%# <img src="app_store_badge.svg"> %></a>
          <hr class="divider"/>
          <div class="subscribe-text">
            <p>Подпишитесь на обновления</p>
          </div>
          <div class="subscribe">
            <%= form_for @conn, prospect_path(@conn, :create), [as: :prospect], fn f -> %>
              <%= text_input f, :email, class: "email-input", placeholder: "Email"%>
              <%= submit "OK", class: "email-submit-button"%>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="footer-container">
  <p class ="privacy-link-text">Радиоскоп © 2017  |  <a class="privacy-link" href="/privacy">Политика Конфиденциальности</a><p>
</div>

web/templates/landing_page/privacy.html.eex
<div class="privacy-container">
<h2 class="privacy-header">Политика Конфиденциальности</h2>
  <p class="privacy-text">
  Настоящие Правила определяют порядок обработки и защиты информации о физических лицах, пользующихся услугами приложения Радиоскоп (далее - Приложение) и его сервисов (далее - Пользователи).<br><br>
  Действующая редакция Правил, являющихся публичным документом, доступна любому пользователю сети Интернет при переходе по ссылке http://rusradio.plus/privacy. В этот документ могут вноситься изменения.
  <h3>1. Состав информации о пользователях</h3>
  <div class="indent">
    Приложение осуществляет обработку информации о Пользователях, которое включает в себя уникальный индетификатор (UUID) который создается в приложение.<br>
    Приложение может также обрабатывать иную информацию о Пользователях, которая включает в себя:<br>
    <div class="indent">
      а)Дополнительные данные, получаемые при доступе к Приложению, включающие в себя данные о технических средствах (устройствах), технологическом взаимодействии с Приложением (в т.ч. IP-адрес хоста, вид операционной системы пользователя, тип браузера, географическое положение, поставщик услуг Интернета, данные из адресной книги, данные, полученные в результате доступа к камере, микрофону и т.п. устройств), и последующих действиях Пользователя на Сайте.<br>
      б)Информация, полученная в результате действий Пользователя в Приложении(в частности, использование радиостанций, длительность проигрывания).
    </div>
  </div>
  <h3>2. Обработка информации о пользователях</h3>
  <div class="indent">
    Обработка персональных данных осуществляется на основе принципов:<br>
    <div class="indent">
      а)законности целей и способов обработки персональных данных;<br>
      б)добросовестности;
    </div>
  </div>
  <h3>3. Сбор персональных данных</h3>
    <div class="indent">
      Сбор персональных данных Пользователя осуществляется при использовании приложения.
    </div>
  <h3>4. Хранение и использование персональных данных</h3>
    <div class="indent">
      Персональные данные пользователей хранятся исключительно на электронных носителях и обрабатываются с использованием автоматизированных систем, за исключением случаев, когда неавтоматизированная обработка персональных данных необходима в связи с исполнением требований законодательства.
    </div>
  <h3>5.Ограничение действия Правил</h3>
    <div class="indent">
      Действие настоящих Правил не распространяется на действия и интернет-ресурсы третьих лиц.
    </div>
</p>
</div>

web/templates/landing_page/privacy_eng.html.eex
<div class="privacy-container">
<h2 class="privacy-header">Privacy Policy</h2>
  <p class="privacy-text">
  These rules determine the method of processing and protecting information on the individuals using the application named Radio (hereinafter the Application) and its services. The purpose of these Rules is to ensure due protection of the user information, including personal data, from unauthorized access and disclosure<br><br>
  The current version of the Rules, which are a public document, is available to any Internet user by clicking http://rusradio.plus/privacy/eng
  This document can be modified. The administration shall notify the users by posting a new version of the Rules on the site at http://rusradio.plus/privacy<br><br>
  By using the Application the User agrees with the conditions of these Rules.

  <h3>1. Purposes of information processing</h3>
  <div class="indent">
    The Application Administration processes information on the Users, including their personal data, in order to fulfill the Application Administration’s obligations to the Users regarding use of the Application and its services.
    <div class="indent">
      The Users personal data include:<br>
      a)Data that are provided by the Users and are minimally necessary for using the Application, including but not limited to: data about the device used to access the application, data about the interaction between the device and the Application, operating system version, geographic region, and actions taken in the Application.
    </div>
  </div>
  <h3>2. Processing of the user information</h3>
  <div class="indent">
    The personal data are processed according to the following principles:<br>
    <div class="indent">
      а)lawful purposes and methods of personal data processing;<br>
      b)good faith;
    </div>
  </div>
  <h3>3.Rights and obligations</h3>
    <div class="indent">
      a)If the user does not accept this policy, the user can opt out by uninstalling the application.<br>
      b)User agrees to use the Application for personal non-commercial purposes.<br>
      c)It is forbidden to offer services related to the use of the Application to other Users for the purpose of making a profit. It is prohibited to use any automatic scripts (“robots”)or other means that allow you to interact with the Application without the participation of the User. It is forbidden to take actions aimed at disrupting the normal functioning of the Application and to use special programs containing malicious components (“viruses”).<br>
      d)The developers of the Application can change the functionality and interface of the Application with or without notifying end users.
    </div>
</p>
  <h3>4.Limitation of the Rules, applicability</h3>
    <div class="indent">
      These Rules do not apply to the actions and Internet resources of third parties.
      The Site Administration bears no liability for the actions of third parties which is the result of using the Internet or the Application Services.
    </div>
</p>
</div>